[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Track rFool target
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
if card.config.center.set == 'Tarot' or card.config.center.set == 'Planet' then 
  G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
      G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
          G.GAME.last_tarot_planet = card.config.center_key
            return true
        end
      }))
        return true
    end
  }))
'''
position = "after"
payload = '''
else
  G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
      G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
          G.GAME.yart_last_other = card.config.center_key
            return true
        end
      }))
        return true
    end
  }))
'''
match_indent = true
# Incantation patch for above
[[patches]]
[patches.pattern]
target = '=[SMODS incantation "Incantation.lua"]'
pattern = '''
if card.config.center.set == 'Tarot' or card.config.center.set == 'Planet' then 
  G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
      G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
          G.GAME.last_tarot_planet = card.config.center_key
            return true
        end
      }))
        return true
    end
  }))
'''
position = "after"
payload = '''
else
  G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
      G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
          G.GAME.yart_last_other = card.config.center_key
            return true
        end
      }))
        return true
    end
  }))
'''
match_indent = true

# Save value for rHermit
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "ease_dollars(G.GAME.current_round.dollars)"
position = "after"
payload = "G.GAME.last_cash_out = G.GAME.current_round.dollars -- Required for correct behavior on cash out screen"
match_indent = true
